steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - 'build'
      - 'gcr.io/$PROJECT_ID/asistente'
      - '--builder'
      - 'gcr.io/buildpacks/builder:v1'
      - '--env'
      - 'PORT=8080'
  
  # Deploy to Cloud Run with gcloud
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'asistente'
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '512Mi'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest,TOKKO_API_KEY=tokko-api-key:latest'
      - '--port'
      - '8080'
      - '--timeout'
      - '600'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--concurrency'
      - '80'

timeout: '900s'
images:
  - 'gcr.io/$PROJECT_ID/asistente'