steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/asistente-altamirano', '.']
    timeout: '1800s'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/asistente-altamirano']
    timeout: '1800s'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'asistente-altamirano'
      - '--image'
      - 'gcr.io/$PROJECT_ID/asistente-altamirano'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--service-account'
      - '${_SERVICE_ACCOUNT}'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'OPENAI_API_KEY=${_OPENAI_API_KEY},TOKKO_API_KEY=${_TOKKO_API_KEY},SECURE_HEADERS=true'
    timeout: '1800s'

images:
  - 'gcr.io/$PROJECT_ID/asistente-altamirano'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _OPENAI_API_KEY: ${_OPENAI_API_KEY}
  _TOKKO_API_KEY: ${_TOKKO_API_KEY}
  _SERVICE_ACCOUNT: asistente-altamirano-sa@asistente-ia-altamirano.iam.gserviceaccount.com